#!/bin/sh

if ! type paru > /dev/null; then
	echo "Paru is not installed"
	echo "Installing paru"

	cd /tmp
	git clone https://aur.archlinux.org/paru-bin.git
	cd paru-bin
	makepkg -si
	cd
fi

echo "Installing fish, wezterm and terminal apps"
paru -S fish wezterm neovim bat eza zoxide starship fzf fd trash-cli downgrade

echo "Installing qtile, picom"
paru -S qtile xcb-util-cursor picom

echo "Installing gui apps and tools"
paru -S thunar thunar-archive-plugin thunar-volman tumbler gvfs xarchiver xfce-polkit udisks2 udiskie dunst

echo "Installing fonts"
paru -S ttf-dm-mono-git noto-fonts-{cjk, emoji}

echo "Installing themes"
paru -S gruvbox-material-icon-theme-git gruvbox-material-gtk-theme-git xcursor-simp1e-gruvbox-light

echo "Finished"
echo "Don't forget to install xorg, nvidia, login manager, networking and audio"
